version: "3"
services:
  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - 27017:27017
  infopipeline:
    image: com.basf/infopipeline
    ports:
      - 8080:8080
    links:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/test
